SYSTEM:
    PRINT_FREQ: 10
DATA:
    BATCH_SIZE: 48
    DATASET: 'MiniTest'
    DATA_PATH: '../../FERdatasets/MiniTest'

MODEL:
    ARCH: 'RepVGGplus-L2pse'
    NUM_CLASS: 1000
    
MODE:
    FINETUNE: True
    
TRAIN:
    START_EPOCH: 8
    EPOCHS: 10
    RESUME: './model/pretrain/RepVGGplus-L2pse.pth'
    CRITERION:
        NAME: 'SoftTargetCE'
    